name       : rubyntlm
version    : 0.6.2
release    : 3
source     :
    - https://rubygems.org/downloads/rubyntlm-0.6.2.gem : be81d7cbe7042c3a582299d89f0b07ef142b9854d260b648b498ad49a7eecbdc
license    : MIT
component  : programming.ruby
summary    : RubyGem - rubyntlm
description: |
    Ruby/NTLM provides message creator and parser for the NTLM authentication.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
